{
 "title": "Order Viewer Service Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"[45]..\"}[1m]))\r\n/\r\nsum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(db_query_duration_seconds_sum[1m])\r\n/\r\nrate(db_query_duration_seconds_count[1m])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cache_hits_total[1m]) /\r\n(rate(cache_hits_total[1m]) + rate(cache_misses_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(kafka_processing_errors_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(kafka_messages_processed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP p95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(http_request_duration_seconds_bucket[5m])) by (le)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{method}} {{path}}" }
   ]
  }
 ]
}